### ISSUE TITLE
无法转换2024年2月9日

### ISSUE THREAD

**Issue by Antares0982** [CutePandaSh/zhdate#10]
```
❯ python3                 
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zhdate import ZhDate
>>> ZhDate.today()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.11/site-packages/zhdate/__init__.py", line 164, in today
    return ZhDate.from_datetime(datetime.now())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/zhdate/__init__.py", line 160, in from_datetime
    return ZhDate(lunar_year, lunar_month, lunar_day, leap_month)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/zhdate/__init__.py", line 111, in __init__
    raise TypeError('农历日期不支持，超出农历1900年1月1日至2100年12月29日，或日期不存在')
TypeError: 农历日期不支持，超出农历1900年1月1日至2100年12月29日，或日期不存在
```
```
❯ pip install --upgrade zhdate
Requirement already satisfied: zhdate in ./venv/lib/python3.11/site-packages (0.1)
```

**Comment by EillesWan** [comment]
此问题已经在 #6  Release 1.0 中修复，尚未推送pypi。 This problem has been fixed in release 1.0( #6 ), but not push to pypi yet.
请使用 you may use this way below to update and fix in your computer.
```bash
git clone https://github.com/CutePandaSh/zhdate.git
cd zhdate
python setup.py install
```
以更新之。

**Comment by Antares0982** [comment]
请问作者是否有考虑更新到pypi呢？每次手动安装挺麻烦的

**Comment by Vic-Chang** [comment]
請問 pypi 沒有 windows 的 distribution 嗎?

ERROR: Could not find a version that satisfies the requirement zhdate==1.0 (from versions: 1.0.macosx-11.0-arm64, 0.1)

version: python 3.11.7

**Comment by Antares0982** [comment]
> 請問 pypi 沒有 windows 的 distribution 嗎?
> 
> ERROR: Could not find a version that satisfies the requirement zhdate==1.0 (from versions: 1.0.macosx-11.0-arm64, 0.1)
> 
> version: python 3.11.7
> 

您应该开一个单独的issue而不是在其他人的issue下方回复无关的内容

**Comment by EillesWan** [comment]
> 请问作者是否有考虑更新到pypi呢？每次手动安装挺麻烦的

确实……

但是作者确实没有把这个内容推送pypi，我也不太清楚他的具体考虑，应该是有其他的事吧？
